Co committee
openstates/openstates-scrapers pull request #3825
Opened 2021-10-05 16:29 UTC by dcliner

2021-10-05 16:33 UTC, dcliner commented
The committee section for colorado was added in the co_committee branch

2021-10-06 18:33 UTC, jamesturk commented on scrapers_next/al/committees.py
> -                com.extras["Room"] = info.text_content().strip()
this change was probably an accident, let's revert it

2021-10-06 18:38 UTC, jamesturk requested changes
looking better, a couple of issues

make sure you run the entire scraper like this:

`poetry run spatula scrape scrapers_next.co.committes` that'll use the list page to get the URLs for the detail page (see the inline note on one issue there)

you'll also find that you need to handle other committee chambers (Joint Committee Year Round Committee comes up quickly for instance)  if it isn't upper or lower it should be `"legislature"` which means that the committee is just part of the legislature, not one chamber or the other

2021-10-06 18:38 UTC, jamesturk commented on scrapers_next/co/committees.py
> +            name, source="https://leg.colorado.gov/content/committees")
this line is setting the CommitteeDetails source to the list page, when you want the `href` value

2021-10-13 19:41 UTC, jamesturk commented
Just gave this a run, it finishes if you pass --timeout 30 as an option, the pages are just slow.

`spatula scrape scrapers_next.co.committees --timeout 30`

The data however is missing legislators, it looks like only the first legislator is grabbed.

2021-11-08 16:55 UTC, closed without merging