AK: Split Sponsorship by Chamber
openstates/openstates-scrapers pull request #5036
Opened 2024-09-18 15:47 UTC by braykuka

- issue [1232](https://github.com/openstates/issues/issues/1232)
- split sponsorship by chamber
- fix the conference_committee_list_url issue

2024-09-18 15:48 UTC, braykuka commented
@NewAgeAirbender Please review it.

2024-09-26 08:31 UTC, braykuka commented
@jessemortenson Please review it.

2024-09-27 04:54 UTC, jessemortenson commented
Thanks, code looks OK, but I am seeing some sponsorship data that is expected but not showing up in the JSON output data. In the Open States database, we have at least one sponsor for almost all the bills in the Alaska (AK) session `33`. (only one bill in the DB is missing a sponsor).

In the JSON data produced by the scrape on this branch, I am seeing 275 files where `sponsorships` is an empty array. So for 274 of those bills/files, I am expecting at least one sponsor to be in that array.

Here's the data that's in the database currently for those bills, to give you an idea of what I'm expecting:

```
+----------+----------------------------------------------+------------+-------+
|identifier|sponsor_name                                  |entity_type |primary|
+----------+----------------------------------------------+------------+-------+
|HB 105    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SJR 21    |SENATE TRANSPORTATION                         |organization|true   |
|SB 193    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 265    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|HB 399    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HB 315    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HR 6      |HOUSE RULES                                   |organization|true   |
|HCR 26    |HOUSE RULES                                   |organization|true   |
|HB 190    |HOUSE WAYS & MEANS                            |organization|true   |
|HB 313    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HB 289    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SCR 34    |SENATE FINANCE                                |organization|true   |
|SCR 40    |SENATE RULES                                  |organization|true   |
|SCR 21    |SENATE RESOURCES                              |organization|true   |
|HB 181    |HOUSE JUDICIARY                               |organization|true   |
|HB 132    |HOUSE JUDICIARY                               |organization|true   |
|HB 131    |HOUSE JUDICIARY                               |organization|true   |
|HR 4      |HOUSE RULES                                   |organization|true   |
|HB 393    |HOUSE RESOURCES                               |organization|true   |
|SB 76     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 71     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|HB 40     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 117    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 50     |SENATE RESOURCES                              |organization|true   |
|SB 224    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 226    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SCR 23    |SENATE FINANCE                                |organization|true   |
|HB 59     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 58     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SCR 101   |SENATE RULES                                  |organization|true   |
|SB 120    |SENATE EDUCATION                              |organization|true   |
|SB 145    |SENATE LABOR & COMMERCE                       |organization|true   |
|HB 199    |HOUSE TRANSPORTATION                          |organization|true   |
|SB 65     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SSCR 10   |SENATE RULES                                  |organization|true   |
|SB 86     |SENATE FINANCE                                |organization|true   |
|HB 79     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HB 87     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 83     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 105    |SENATE TRANSPORTATION                         |organization|true   |
|HB 92     |HOUSE FISHERIES                               |organization|true   |
|HB 85     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SCR 29    |SENATE LABOR & COMMERCE                       |organization|true   |
|SB 97     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 85     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|HB 58     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 202    |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|HCR 20    |HOUSE RULES                                   |organization|true   |
|HB 130    |HOUSE JUDICIARY                               |organization|true   |
|HB 140    |HOUSE RULES BY REQUEST                        |organization|true   |
|HB 119    |HOUSE RULES BY REQUEST                        |organization|true   |
|SB 123    |SENATE TRANSPORTATION                         |organization|true   |
|SB 66     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 155    |SENATE FINANCE                                |organization|true   |
|SSCR 8    |SENATE RULES                                  |organization|true   |
|SB 126    |SENATE LABOR & COMMERCE                       |organization|true   |
|HB 158    |HOUSE MILITARY & VETERANS' AFFAIRS            |organization|true   |
|SB 107    |SENATE FINANCE                                |organization|true   |
|SB 41     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 122    |SENATE RULES                                  |organization|true   |
|HB 54     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SCR 18    |SENATE COMMUNITY & REGIONAL AFFAIRS           |organization|true   |
|SCR 28    |SENATE JUDICIARY                              |organization|true   |
|HB 49     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HB 165    |HOUSE WAYS & MEANS                            |organization|true   |
|HB 41     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|HB 75     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 114    |SENATE RULES                                  |organization|true   |
|SB 64     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|SB 68     |SENATE RESOURCES                              |organization|true   |
|HB 178    |HOUSE FINANCE                                 |organization|true   |
|SB 98     |SENATE FINANCE                                |organization|true   |
|SB 262    |SENATE STATE AFFAIRS                          |organization|true   |
|HB 74     |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 81     |SENATE RULES BY REQUEST OF LEGISLATIVE COUNCIL|organization|true   |
|SJR 8     |SENATE RESOURCES                              |organization|true   |
|HB 141    |HOUSE RULES                                   |organization|true   |
|SCR 26    |SENATE HEALTH & SOCIAL SERVICES               |organization|true   |
|SSCR 11   |SENATE RULES                                  |organization|true   |
|SB 234    |SENATE LABOR & COMMERCE                       |organization|true   |
|HB 128    |HOUSE TRANSPORTATION                          |organization|true   |
|SB 183    |SENATE LABOR & COMMERCE                       |organization|true   |
|HB 312    |HOUSE RULES BY REQUEST OF THE GOVERNOR        |organization|true   |
|SB 54     |SENATE RULES BY REQUEST OF THE GOVERNOR       |organization|true   |
|HB 160    |HOUSE WAYS & MEANS                            |organization|true   |
|HJR 8     |HOUSE WAYS & MEANS                            |organization|true   |
|HCR 22    |HOUSE RULES                                   |organization|true   |
|HCR 18    |HOUSE LABOR & COMMERCE                        |organization|true   |
|SB 96     |SENATE  [...]

2024-09-27 14:32 UTC, braykuka commented
@jessemortenson There was an issue to get the sponsors. Please review it now.

2024-09-30 19:15 UTC, jessemortenson requested changes
Thank you for fixing the missing organizational sponsorships. I have two more small requests regarding how those org sponsorships are coming through.

2024-09-30 19:15 UTC, jessemortenson commented on scrapers/ak/bills.py
>                      bill.add_sponsorship(
Can you please add logic here that adds the `chamber` argument for bills sponsored by an organization? It looks like every organization name starts with either `SENATE` or `HOUSE`, so if `SENATE` then `chamber=upper` and if `HOUSE` then `chamber=lower`

2024-09-30 19:15 UTC, jessemortenson commented on scrapers/ak/bills.py
>                  if re.match(r" BY REQUEST OF THE GOVERNOR$", spons_str):
Looks like about half of the organizational sponsorships still include the `by request...` language in the `name` property. Can you please check this and adjust logic to try to strip it out in all cases?

```
jesse@greenbookwork:~/repo/openstates/braykuka/openstates-scrapers/scrapers/_data/ak$ rg -ic "by request" | wc -l
122
```

```
 SELECT bill_identifier, "name", "primary", organization_id  FROM bill_sponsorships WHERE entity_type = 'organization' AND lower(name) LIKE '%request%' ORDER BY bill_identifier, name;
┌─────────────────┬────────────────────────────────────────────────┬─────────┬───────────────────────────────────────────────────────────────────┐
│ bill_identifier │                      name                      │ primary │                          organization_id                          │
├─────────────────┼────────────────────────────────────────────────┼─────────┼───────────────────────────────────────────────────────────────────┤
│ HB105           │ HOUSE RULES BY REQUEST OF THE GOVERNOR         │ true    │ "~{\"name\": \"HOUSE RULES BY REQUEST OF THE GOVERNOR\"}"         │
│ HB106           │ HOUSE RULES BY REQUEST OF THE GOVERNOR         │ true    │ "~{\"name\": \"HOUSE RULES BY REQUEST OF THE GOVERNOR\"}"         │
│ HB119           │ HOUSE RULES BY REQUEST                         │ true    │ "~{\"name\": \"HOUSE RULES BY REQUEST\"}"                         │
│ HB140           │ HOUSE RULES BY REQUEST                         │ true    │ "~{\"name\": \"HOUSE RULES BY REQUEST\"}"                         │
│ HB146           │ HOUSE RULES BY REQUEST OF THE GOVERNOR         │ true    │ "~{\"name\": \"HOUSE RULES BY REQUEST OF THE GOVERNOR\"}"         │
```

so:

- `HOUSE RULES BY REQUEST OF THE GOVERNOR` should just be `HOUSE RULES`
- `HOUSE RULES BY REQUEST` should just be `HOUSE RULES`
- `SENATE RULES BY REQUEST OF LEGISLATIVE COUNCIL` should just be `SENATE RULES`

2024-09-30 19:46 UTC, jessemortenson commented on scrapers/ak/bills.py
>                          primary=True,
Oops, one more issue I found is that sometimes the scraper says that two sponsors are primary, even though only one sponsor should be primary in those cases. What I noticed is that this happens when there are both House and Senate sponsors for a bill (upper and lower): in that case the first person in each list is marked `primary` by the scraper.

Instead, it should be: if a House bill, only first House sponsor should be primary=True, and if a Senate bill, only the first Senate sponsor should be primary=True

EG 

  - only WRIGHT should be a primary sponsor on https://www.akleg.gov/basis/Bill/Detail/33?Root=HB126
  - only KIEHL should be a primary sponsor on https://www.akleg.gov/basis/Bill/Detail/33?Root=sb10

2024-10-01 16:07 UTC, braykuka commented
@jessemortenson Thanks for your review. I've fixed those issues now. 
Actually I couldn't see the sponsor's chamber value in the json files though I've added it in the code. 
![image](https://github.com/user-attachments/assets/81299355-aba8-4365-8cd1-a164c72fd545)
Please let me know if you have still issues.

2024-10-04 20:40 UTC, jessemortenson approved these changes
Looks good to me, thank you!

2024-10-04 20:42 UTC, jessemortenson commented
> @jessemortenson Thanks for your review. I've fixed those issues now. Actually I couldn't see the sponsor's chamber value in the json files though I've added it in the code. ![image](https://private-user-images.githubusercontent.com/81768784/372554938-81299355-aba8-4365-8cd1-a164c72fd545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzQ3MTgsIm5iZiI6MTcyODA3NDQxOCwicGF0aCI6Ii84MTc2ODc4NC8zNzI1NTQ5MzgtODEyOTkzNTUtYWJhOC00MzY1LThjZDEtYTE2NGM3MmZkNTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIwNDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMDhiM2EwNDRiNzc4YzAwYTA1ZWJmOWE4MjQzZGM1ZTc1ZGY1NDE1NDg5NGFlMzJlMzYxNTlkOTcwODJjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UyWh6gMOQC4xIfiI6LmUEJPr9VdnnAk8RxE0b5CEPGI) Please let me know if you have still issues.

Ah, I think you may need to sync updates from the upstream repository (and run `poetry install` again). We have added more recent changes to the `openstates-core` library that causes these chamber values to be emitted in the JSON files, and only more recent versions of `openstates-scrapers` have specified the newest version of `openstates-core`.  (I ran these test scrapes with `openstates=6.20.5` in order to get chamber values showing up in the JSON output). We have been iterating actively on that code in recent weeks.

2024-10-04 20:42 UTC, merged